import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import matter from 'gray-matter';
import { marked } from 'marked';

const root = process.cwd();
const langs = ['en', 'ru'];
const outDir = path.join(root, 'src', 'generated');

marked.setOptions({ gfm: true, breaks: false });

async function readMarkdown(filePath) {
  const raw = await readFile(filePath, 'utf8');
  const parsed = matter(raw);
  return {
    meta: parsed.data,
    html: marked.parse(parsed.content).trim(),
    text: parsed.content.trim(),
  };
}

async function readWork(lang) {
  const workDir = path.join(root, 'content', lang, 'work');
  const files = (await readdir(workDir)).filter((file) => file.endsWith('.md')).sort();
  const priority = { primary: 0, supporting: 1 };
  const items = await Promise.all(
    files.map(async (file) => {
      const slug = file.replace(/\.md$/, '');
      const item = await readMarkdown(path.join(workDir, file));
      return {
        slug,
        title: String(item.meta.title ?? slug),
        priority: String(item.meta.priority ?? 'supporting'),
        url: String(item.meta.url ?? ''),
        redditUrl: item.meta.redditUrl ? String(item.meta.redditUrl) : '',
        stack: String(item.meta.stack ?? ''),
        html: item.html,
      };
    }),
  );

  return items.sort((a, b) => {
    const priorityDelta = (priority[a.priority] ?? 9) - (priority[b.priority] ?? 9);
    return priorityDelta || a.title.localeCompare(b.title);
  });
}

const content = {};

for (const lang of langs) {
  const hero = await readMarkdown(path.join(root, 'content', lang, 'hero.md'));
  const proof = await readMarkdown(path.join(root, 'content', lang, 'proof.md'));
  const stack = await readMarkdown(path.join(root, 'content', lang, 'stack.md'));
  const contact = await readMarkdown(path.join(root, 'content', lang, 'contact.md'));
  const work = await readWork(lang);

  content[lang] = {
    hero: { ...hero.meta, html: hero.html },
    proof: { ...proof.meta, html: proof.html },
    stack: { ...stack.meta, html: stack.html },
    contact: { ...contact.meta, html: contact.html },
    work,
  };
}

const moduleText = `// Generated by scripts/build-content.mjs. Do not edit manually.\n\nexport const siteContent = ${JSON.stringify(content, null, 2)} as const;\n`;

await mkdir(outDir, { recursive: true });
await writeFile(path.join(outDir, 'content.ts'), moduleText, 'utf8');
